#!/bin/bash
# Step 1 of the training-species protein pipeline.
#
# For each of the 68 vertebrate training species:
#   1. Extract Tiberius ab initio peptides (from tiberius/tiberius_seqlen.gtf).
#   2. Diamond blastp peptides vs. the order-excluded ODB to rank protein donor species.
#   3. Extract proteins from the top-4 closest species → protein_top4.fa.
#
# The ODB is never written to disk: the order-exclusion set is computed once
# (BFS on nodes.dmp), embedded into a temp Python filter script on /tmp, and
# used to stream Vertebrata.fa.gz directly into diamond makedb and protein
# extraction.  Two read passes over the shared ODB instead of 68 per-species gz
# copies.
#
# Requires:
#   results/training_vertebrates_v2/species_order_taxids.tsv
#   (generated by: python scripts/lookup_order_taxids.py ... )
#
# Output per species (${RESULTS_DIR}/${species}/proteins/):
#   tiberius_peptides.fa          gffread extraction from tiberius_seqlen.gtf
#   diamond_db.dmnd               Diamond DB built from order-excluded ODB stream
#   diamond_hits.tsv              blastp output
#   species_rank.tsv              all species ranked by total bitscore
#   top_species.txt               top-4 species taxids (one per line)
#   protein_top4.fa               proteins from those 4 species
#
#SBATCH --job-name=prep_prot_train
#SBATCH --partition=snowball,pinky,batch
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --time=24:00:00
#SBATCH --array=0-67%10
#SBATCH --output=/projects/AI-GUSTUS/tiberius_orf_finder/logs/prep_prot_train_%A_%a.out
#SBATCH --error=/projects/AI-GUSTUS/tiberius_orf_finder/logs/prep_prot_train_%A_%a.err

set -euo pipefail
source /etc/profile.d/modules.sh
module load singularity/3.11.3

PROJDIR=/projects/AI-GUSTUS/tiberius_orf_finder
RESULTS_DIR=${PROJDIR}/results/training_vertebrates_v2
ODB_GZ=/home/gabriell/tiberius_proteins_analysis/odb/raw/Vertebrata.fa.gz
NODES_DMP=/home/gabriell/tiberius_proteins_analysis/odb/nodes.dmp
TIBERIUS_REPO=/home/gabriell/Tiberius
TAXIDS_TSV=${RESULTS_DIR}/species_order_taxids.tsv
SIF=${PROJDIR}/sif/tiberius_2.0.2.sif
TOP_N=4
CPUS=${SLURM_CPUS_PER_TASK:-16}

mkdir -p "${PROJDIR}/logs"

declare -a SPECIES=(
    "Acipenser_ruthenus"
    "Alligator_mississippiensis"
    "Alosa_sapidissima"
    "Amblyraja_radiata"
    "Anguilla_anguilla"
    "Anolis_sagrei"
    "Apus_apus"
    "Bombina_bombina"
    "Carcharodon_carcharias"
    "Corvus_hawaiiensis"
    "Dendropsophus_ebraccatus"
    "Denticeps_clupeoides"
    "Elgaria_multicarinata_webbii"
    "Emys_orbicularis"
    "Erpetoichthys_calabaricus"
    "Esox_lucius"
    "Eublepharis_macularius"
    "Falco_peregrinus"
    "Gavia_stellata"
    "Labrus_mixtus"
    "Latimeria_chalumnae"
    "Lepisosteus_oculatus"
    "Megalops_cyprinoides"
    "Mobula_birostris"
    "Narcine_bancroftii"
    "Osmerus_eperlanus"
    "Parambassis_ranga"
    "Pelobates_fuscus"
    "Podarcis_raffonei"
    "Rana_temporaria"
    "Rhinatrema_bivittatum"
    "Scleropages_formosus"
    "Solea_solea"
    "Sparus_aurata"
    "Aotus_nancymaae"
    "Camelus_bactrianus"
    "Canis_lupus_familiaris"
    "Cavia_porcellus"
    "Cebus_capucinus"
    "Ceratotherium_simum"
    "Chinchilla_lanigera"
    "Condylura_cristata"
    "Desmodus_rotundus"
    "Dipodomys_ordii"
    "Enhydra_lutris"
    "Eptesicus_fuscus"
    "Equus_caballus"
    "Heterocephalus_glaber"
    "Ictidomys_tridecemlineatus"
    "Jaculus_jaculus"
    "Loxodonta_africana"
    "Marmota_marmota"
    "Microcebus_murinus"
    "Microtus_ochrogaster"
    "Mus_musculus"
    "Mus_pahari"
    "Neomonachus_schauinslandi"
    "Ochotona_princeps"
    "Octodon_degus"
    "Odobenus_rosmarus"
    "Otolemur_garnettii"
    "Panthera_pardus"
    "Propithecus_coquereli"
    "Puma_concolor"
    "Rattus_norvegicus"
    "Saimiri_boliviensis"
    "Sorex_araneus"
    "Trichechus_manatus"
)
species=${SPECIES[$SLURM_ARRAY_TASK_ID]}
GENOME=${RESULTS_DIR}/${species}/assembly/genome.fa
TIB_GTF=${RESULTS_DIR}/${species}/tiberius/tiberius_seqlen.gtf
OUT_DIR=${RESULTS_DIR}/${species}/proteins

echo "[$(date -Iseconds)] species=${species}"

for f in "${ODB_GZ}" "${NODES_DMP}" "${TAXIDS_TSV}"; do
    [[ -s "${f}" ]] || { echo "ERROR: missing ${f}" >&2; exit 2; }
done
[[ -s "${GENOME}" ]] || { echo "SKIP ${species}: missing genome.fa" >&2; exit 0; }
[[ -s "${TIB_GTF}" ]] || { echo "SKIP ${species}: missing tiberius_seqlen.gtf" >&2; exit 0; }

if [[ -s "${OUT_DIR}/protein_top4.fa" && "${FORCE:-0}" != "1" ]]; then
    echo "SKIP ${species}: protein_top4.fa already exists"
    exit 0
fi

mkdir -p "${OUT_DIR}"

run_tool() {
    singularity exec \
        --bind /projects/AI-GUSTUS,/home/gabriell \
        "${SIF}" "$@"
}

# ── Read order_taxid from TSV ─────────────────────────────────────────────────
ORDER_TAXID=$(awk -F'\t' -v sp="${species}" '$1 == sp {print $4; exit}' "${TAXIDS_TSV}")
if [[ -z "${ORDER_TAXID}" ]]; then
    echo "ERROR: ${species} not found in ${TAXIDS_TSV}" >&2; exit 2
fi
echo "[$(date -Iseconds)] order_taxid=${ORDER_TAXID}"

# ── Build a per-job ODB filter script on local /tmp ───────────────────────────
# BFS on nodes.dmp to find all taxids in the order subtree; embed the resulting
# set as a Python literal into a small script.  The script reads FASTA from
# stdin and writes only records whose taxid is NOT in the exclusion set.
# Optional argv[1]: path to a file of wanted taxids — when given, also
# restricts output to those taxids (used for the protein_top4 extraction pass).
FILTER_SCRIPT=$(mktemp "${TMPDIR:-/tmp}/filter_odb_XXXXXX.py")
trap "rm -f ${FILTER_SCRIPT}" EXIT

python3 - "${ORDER_TAXID}" "${NODES_DMP}" "${FILTER_SCRIPT}" <<'PYEOF'
import sys, re
from collections import deque

order_taxid = int(sys.argv[1])
nodes_dmp   = sys.argv[2]
out_py      = sys.argv[3]

parent_of = {}
with open(nodes_dmp) as fh:
    for line in fh:
        p = [x.strip() for x in line.rstrip('\n').split('|')]
        if len(p) >= 2:
            parent_of[int(p[0])] = int(p[1])

children_of = {}
for tid, par in parent_of.items():
    children_of.setdefault(par, []).append(tid)

excl = set()
queue = deque([order_taxid])
while queue:
    cur = queue.popleft()
    excl.add(cur)
    for child in children_of.get(cur, []):
        if child not in excl:
            queue.append(child)

print(f'  {len(excl)} taxids in exclusion set for order {order_taxid}', flush=True)

script = f'''import sys, re

EXCL = {repr(excl)}

wanted = None
if len(sys.argv) > 1:
    wanted = set()
    with open(sys.argv[1]) as fh:
        for line in fh:
            line = line.strip()
            if line:
                wanted.add(int(line))

pat = re.compile(r"^>(\\d+)_")
keep = False
for line in sys.stdin:
    if line.startswith(">"):
        m = pat.match(line)
        if m:
            tid = int(m.group(1))
            keep = tid not in EXCL and (wanted is None or tid in wanted)
        else:
            keep = True
        if keep:
            sys.stdout.write(line.replace('\\t', ' '))
    elif keep:
        sys.stdout.write(line)
'''

with open(out_py, 'w') as fh:
    fh.write(script)
PYEOF

# Usage:
#   zcat ODB | python3 "${FILTER_SCRIPT}"            → exclude order only
#   zcat ODB | python3 "${FILTER_SCRIPT}" top.txt    → exclude order + keep wanted

# ── Step 1: extract Tiberius peptides ─────────────────────────────────────────
PEPTIDES="${OUT_DIR}/tiberius_peptides.fa"

if [[ ! -s "${PEPTIDES}" ]]; then
    echo "[$(date -Iseconds)] Extracting Tiberius peptides …"
    run_tool gffread "${TIB_GTF}" -g "${GENOME}" -y "${PEPTIDES}"
    N=$(grep -c '^>' "${PEPTIDES}" || true)
    echo "[$(date -Iseconds)]   ${N} peptides"
else
    echo "[$(date -Iseconds)] Reusing ${PEPTIDES}"
fi

# ── Step 2: Diamond db + blastp ───────────────────────────────────────────────
DIAM_DB="${OUT_DIR}/diamond_db"
DIAM_HITS="${OUT_DIR}/diamond_hits.tsv"

if [[ ! -s "${DIAM_HITS}" ]]; then
    # diamond makedb needs two read passes over its input; a stdin pipe is not
    # rewindable, so buffer the filtered ODB to a gzip temp file on /tmp
    # (node-local disk, not on project quota; singularity binds /tmp by default).
    FILT_FA=$(mktemp "${TMPDIR:-/tmp}/odb_filtered_XXXXXX.fa.gz")
    trap "rm -f ${FILTER_SCRIPT} ${FILT_FA}" EXIT

    echo "[$(date -Iseconds)] Buffering order-excluded ODB → ${FILT_FA} …"
    zcat "${ODB_GZ}" | python3 "${FILTER_SCRIPT}" | gzip -1 > "${FILT_FA}"
    echo "[$(date -Iseconds)]   $(du -sh "${FILT_FA}" | cut -f1) buffered"

    echo "[$(date -Iseconds)] Building Diamond DB …"
    run_tool diamond makedb \
        --in      "${FILT_FA}" \
        --db      "${DIAM_DB}" \
        --threads "${CPUS}"
    rm -f "${FILT_FA}"

    echo "[$(date -Iseconds)] Running Diamond blastp …"
    run_tool diamond blastp \
        --query           "${PEPTIDES}" \
        --db              "${DIAM_DB}.dmnd" \
        --out             "${DIAM_HITS}" \
        --outfmt 6        qseqid sseqid pident length evalue bitscore qlen slen \
        --evalue          1e-5 \
        --max-target-seqs 200 \
        --very-sensitive \
        --threads         "${CPUS}"
    echo "[$(date -Iseconds)]   $(wc -l < "${DIAM_HITS}") hits"
    rm -f "${DIAM_DB}.dmnd"
else
    echo "[$(date -Iseconds)] Reusing ${DIAM_HITS}"
fi

# ── Step 3: rank top-N donor species ─────────────────────────────────────────
TOP_TXT="${OUT_DIR}/top_species.txt"

if [[ ! -s "${TOP_TXT}" ]]; then
    echo "[$(date -Iseconds)] Ranking species (top ${TOP_N}) …"
    (cd "${OUT_DIR}" && \
     python3 "${TIBERIUS_REPO}/tiberius/scripts/rank_species_from_diamond.py" \
         "${DIAM_HITS}" "${TOP_N}" \
         > "${OUT_DIR}/species_rank.tsv")
    echo "[$(date -Iseconds)] Top ${TOP_N} taxids:"
    cat "${TOP_TXT}"
else
    echo "[$(date -Iseconds)] Reusing ${TOP_TXT}"
fi

# ── Step 4: extract protein_top4.fa (ODB stream pass) ────────────────────────
PROTEIN_TOP4="${OUT_DIR}/protein_top4.fa"

if [[ ! -s "${PROTEIN_TOP4}" ]]; then
    echo "[$(date -Iseconds)] Extracting protein_top${TOP_N}.fa …"
    zcat "${ODB_GZ}" \
        | python3 "${FILTER_SCRIPT}" "${TOP_TXT}" \
        > "${PROTEIN_TOP4}"
    N=$(grep -c '^>' "${PROTEIN_TOP4}" || true)
    echo "[$(date -Iseconds)]   ${N} sequences → ${PROTEIN_TOP4}"
fi

echo "[$(date -Iseconds)] done → ${PROTEIN_TOP4}"
